language: python
addons:
  apt:
    packages:
    - bc
    - findutils
sudo: false
python:
  - '2.7'
  - '3.4'
env:
  - TOX_ENV=unit
  - TOX_ENV=pep8
  - TOX_ENV=pylint
  - TOX_ENV=cover
install:
  - pip install tox
script:
  - if [ $TOX_ENV = unit ]; then PYENV=py$(echo $TRAVIS_PYTHON_VERSION|sed -e 's/^py//' -e 's/\.//'); travis_wait tox -e $PYENV; elif [ $TRAVIS_PYTHON_VERSION = 2.7 ]; then travis_wait tox -e $TOX_ENV; fi
